version: "3.9"
services:
  app:
    build: .
    volumes:
      - medaware_result:/data/output
      - medaware_logs:/tmp/log
volumes:
  medaware_result:
    external: true
  medaware_logs:
    external: true